# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: beta.gouv.fr
email: contact@beta.gouv.fr
description: Nous créons des services publics numériques
baseurl: "" # the subpath of your site, e.g. /blog
url: https://beta.gouv.fr # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: BetaGouv
github_username: betagouv
github_repository: BetaGouv/beta.gouv.fr

# Build settings
markdown: kramdown
strict_front_matter: true
plugins:
  - jekyll-redirect-from

# Permettre de créer des publications datées dans le futur
future: true

# Options du template

lang: fr

include: [
  "_pages",
  "_redirects",
  "_headers",
]
exclude: ["content/templates", "CONTRIBUTING.md", "rb", "vendor"]

copy_to_dest:
  - source: node_modules/remixicon/fonts/.
    target: assets/remixicon/fonts/
  - source: node_modules/@gouvfr/dsfr/dist/css/.
    target: assets/gouvfr/css/
  - source: node_modules/@gouvfr/dsfr/dist/fonts/.
    target: assets/gouvfr/fonts/
  - source: node_modules/@gouvfr/dsfr/dist/js/.
    target: assets/gouvfr/js/

excerpt_separator: <!--more-->

# Collections

collections_dir:
  content

collections:
  authors:
  incubators:
  jobs:
    output: true
    permalink: /recrutement/:year/:month/:day/:title.html
  mooc:
    output: true
    permalink: /approche/formation/mooc/:title.html
  phases:
  fasts:
    output: true
    permalink: /approche/fast/:title.html
  startups:
    output: true
    permalink: /startups/:title.html

defaults:
  - scope:
      path: ""
      type: "jobs"
    values:
      layout: job
      title: Recrutement
  - scope:
      path: ""
      type: "mooc"
    values:
      layout: with-sidebar
      sidebar: sidebar-approche.html
  - scope:
      path: ""
      type: "fasts"
    values:
      layout: with-sidebar
  - scope:
      path: ""
      type: "startups"
    values:
      layout: startup
  - scope:
      path: "img/authors"
    values:
      authors_img: true
  - scope:
      path: "img/startups"
    values:
      startups_img: true
