locale: fr

backend:
  name: github
  site_domain: beta.gouv.fr
  repo: betagouv/beta.gouv.fr
  commit_messages:
    create: Création de {{slug}} dans {{collection}} !
    update: Mise à jour de {{slug}} dans {{collection}}
    delete: Suppression de {{slug}} dans {{collection}}
    uploadMedia: Nouvelle image {{path}}
    deleteMedia: Suppression de l'image {{path}}
  squash_merges: true
  open_authoring: true
  use_graphql: true

# Permet d'expérimenter en local
# cf. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
# local_backend: true

media_folder: "img/netlifycms"

display_url: https://beta.gouv.fr
logo_url: https://beta.gouv.fr/assets/images/favicons/apple-touch-icon-180x180.png

show_preview_links: true

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "."

# Editorial workflow: validate changes through pull requests
publish_mode: editorial_workflow

relation_default_options: &relation_default_options
  widget: relation
  valueField: "{{slug}}"
  displayFields: [title]
  searchFields: [slug, title]

date_field_defaults: &date_field_defaults
  widget: datetime
  format: YYYY-MM-DD
  dateFormat: YYYY-MM-DD
  timeFormat: false
  default: null

collections:
  - name: startups
    publish: false
    label: Produits
    preview_path: "startups/{{slug}}"
    label_singular: Produit
    folder: "content/_startups"
    create: true
    delete: false
    editor:
      preview: false
    fields:
      - label: Quel est le nom de ta Startup d'ETat ?
        name: title
        hint: "Ce nom sert d'identifiant pour la startup et ne doit pas dépasser 30 caractères"
        widget: string
        pattern: ["^.{1,30}$","Vous êtes limité à 20 caractères"]
      - label: Quel est son objectif principal ?
        hint : >
          Par exemple : "Faciliter la création d'une fiche produit". Pas besoin de faire plus long.
        name: mission
        widget: string
      - label: Qui est l'administration sponsor ?
        hint : Indiques le nom de l'administration qui porte ta Startup d'Etat.
        name: owner
        widget: string
      - label: Quelques infos sur la ou les administrations sponsors ou partenaires ? 
        name: sponsors
        widget: list
        collapsed: false
        fields:
          - label: Nom de l'administration
            name: name
            widget: string
          - label: Quel est l'acronyme de cette administration ?
            name: acronym
            widget: string
            required: false
          - label: "Type"
            hint: "Quelle est le type de partenaire ? si vous ne savez pas, vous n'avez pas besoins de compléter"
            name: "type"
            widget: "select"
            required: false
            options:
              - { label: "Administration centrale", value: "administration-centrale" }
              - { label: "Opérateur", value: "operateur" }
              - { label: "Sécurité sociale", value: "securite-sociale" }
              - { label: "Collectivité territoriale ", value: "collectivite-territoriale" }
              - { label: "Autre", value: "autre" }
          - label: "Cette administration intervient principalement dans quel champs de l'action publique ?"
            hint: >
              Quelle est le domaine "ministériel" ou domaine "action publique" du partenaire ? si vous ne savez pas, vous n'avez pas besoins de compléter
            name: "domaine_ministeriel"
            widget: "select"
            required: true
            options:
              - { label: "Affaires étrangères", value: "affaires-etrangeres" }
              - { label: "Affaires sociales", value: "affaires-sociales" }
              - { label: "Agriculture", value: "agriculture" }
              - { label: "Armées", value: "armees" }
              - { label: "Bercy", value: "bercy" }
              - { label: "Culture", value: "culture" }
              - { label: "Education nationnale", value: "education-nat" }
              - { label: "Enseignement supérieur", value: "enseignement-sup" }
              - { label: "Environnement", value: "environnement" }
              - { label: "Intérieur", value: interieur }
              - { label: "Outre-mer", value: "outre-mer" }
              - { label: "Santé", value: "sante" }
              - { label: "Service du Premier Ministre", value: "spm" }
              - { label: "Sport", value: "sport" }
              - { label: "Travail", value: "travail" }
              - { label: "Territoires", value: "territoires" }
              - { label: "Autres", value: "autres" }
      - <<: *relation_default_options
        label: Quel est l'incubateur qui t'accompagne ?
        name: incubator
        collection: incubators
      - label: Lien vers le produit
        name: link
        widget: string
        required: false
      - label: Lien vers le code source
        name: repository
        widget: string
        required: false
      - label: Email de contact
        name: contact
        widget: string
        pattern: ['^[^@\s]+@[^@\s]+\.[^@\s]+$', 'Ce doit être un email valide']
        required: true
      - label: Statistiques d'usage publiques
        name: stats
        widget: boolean
        required: false
      - label: Lien vers la page budget
        name: budget_url
        widget: string
        required: false
      - label: Évènements marquants
        name: events
        label_singular: évènement marquant
        widget: list
        collapsed: false
        fields:
          - label: Type d'évènement
            name: name
            widget: relation
            valueField: "{{slug}}"
            displayFields: ["{{label}} ({{slug}})"]
            searchFields: [slug, label]
            collection: events
          - <<: *date_field_defaults
            label: Date approximative
            name: date
          - label: Commentaire
            name: comment
            widget: string
            required: false
      - label: Phases de la plus ancienne à la plus récente
        name: phases
        label_singular: phase
        widget: list
        hint: Indiquez les étapes de la vie du produit de la plus ancienne à la plus récente.
        collapsed: false
        required: true
        min: 1
        max: 10 # both min and max are required to be apply 
        fields:
          - label: Nom de la phase
            name: name
            widget: relation
            valueField: "{{slug}}"
            displayFields: ["{{label}} ({{slug}})"]
            searchFields: [slug, label]
            collection: phases
          - <<: *date_field_defaults
            label: Date de début
            name: start
          - <<: *date_field_defaults
            label: Date de fin de la phase ou de passage à une autre phase
            name: end
            required: false
          - label: Commentaire
            name: comment
            widget: string
            required: false
      - label: Rédiger sa fiche produit
        name: body
        widget: markdown
        hint: "N'hésite pas à te référer aux autres fiches produit présentes sur le site beta.gouv"
        default: >
          Voici un exemple de format  - N'hésite pas à utiliser les outils de mis-en-forme ou à switcher en markdown ☝️.

          Pour t'aider dans la rédaction de ta fiche produit, nous te recommandons de suivre ce plan: 

          ## Contexte

          Quel est le contexte de ta Startup d'Etat ?

          ## Problème

          Les problèmes que vous avez identifiés ou vos hypothèses de problèmes? Qui en souffre ? quels sont les conséquences de ces problèmes ?

          ## Solution

          Décrit ta solution en quelques lignes? qui seront/sont les bénéficiaires ?

          ## Stratégie

          Comment vous vous y prenez pour atteindre votre usagers ? quel impact chiffré visez-vous ?
      
  - name: "authors"
    publish: false
    identifier_field: fullname
    label: "Membres"
    label_singular: "Membre"
    description: "Les membres de la communauté beta.gouv.fr. Pour modifier une fiche, clique sur son nom ou recherche-la dans la barre de gauche. Pour ajouter un nouveau membre, allez sur le secretariat : https://secretariat.incubateur.net/onboarding ."
    folder: "content/_authors"
    create: false
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Nom complet"
        hint: "Format : Prénom Nom. Ton nom complet est utilisé pour le nom de ta fiche. Attention à ton orthographe !"
        name: "fullname"
        widget: "string"
      - name: domaine
        hint: Dans quel domaine principal interviens-tu ?
        widget: select
        options: [
          "Animation",  
          "Coaching",
          "Déploiement",
          "Design", 
          "Développement",
          "Intraprenariat",
          "Produit", 
          "Autre"
        ]
        required: true
      - label: "Description"
        hint: "Ce que tu veux qu'on dise de toi. Développeuse NodeJS ? Intrapreneur ? Chargée de développement ? Coach construction produit ? Experte en simplicité ?. Tu pourras écrire une bio plus bas"
        name: "role"
        required: true
        widget: "string"
      - label: "Github"
        hint: "Ton nom d'utilisateur GitHub. Il te permet de rejoindre automatiquement l'organisation GitHub betagouv."
        name: "github"
        widget: "string"
        required: false
      - label: "Avatar"
        hint: "À remplir si tu veux mettre un avatar depuis un site externe. Tu peux aussi laisser vide et mettre une image dans le dossier /img/authors/. À défaut, on regardera si tu as une image sur ton profil Github. En dernier, la fiole beta.gouv.fr sera affichée sur la page communauté. Dans le doute : demande à ton marrain !"
        name: "avatar"
        widget: "string"
        required: false
      - label: "Lien externe"
        hint: "Lien vers une page perso externe."
        name: "link"
        widget: "string"
        required: false
      - label: 'Missions'
        label_singular: "Mission"
        hint: "Ton historique de missions avec nous dans l'ordre chronologique."
        name: 'missions'
        widget: 'list'
        min: 1
        max: 10 # both min and max are required to be apply 
        collapsed: false
        fields:
          - label: "Statut"
            hint: "Quelle est ta relation professionnelle avec nous ?"
            name: "status"
            widget: "select"
            options:
              - { label: "Agent public", value: "admin" }
              - { label: "Indépendant", value: "independent" }
              - { label: "Société ou prestataire de services", value: "service" }
          - label: "Employeur"
            hint: "Si besoin de préciser : ton ministère d'origine, ta SSII, etc."
            name: "employer"
            widget: "string"
            required: false
          - <<: *date_field_defaults
            label: "Date de début"
            hint: "Début de ton contrat ou de ton financement."
            name: "start"
          - <<: *date_field_defaults
            label: "Date de fin"
            hint: "Fin de ton contrat ou de ton financement - tu pourras la modifier plus tard."
            name: "end"
      - label: Startups
        label_singular: Startup
        hint: "Plusieurs choix possibles. Si la startup n'apparait pas encore dans la liste, contacte un administrateur du site !"
        name: startups
        <<: *relation_default_options
        collection: startups
        multiple: true
        required: false
      - label: Anciennes Startups
        label_singular: Ancienne Startup
        hint: "Plusieurs choix possibles : sur quelles startups de la communauté tu as travaillé avant ?"
        name: previously
        <<: *relation_default_options
        collection: startups
        required: false
        multiple: true
      - label: Badges
        name: "badges"
        widget: "select"
        multiple: true
        required: false
        options:
           - { label: "Ségur", value: "segur" }
      - label: Mini-Biographie
        hint: "Raconte-nous qui tu es dans une phrase percutante !"
        name: body
        widget: markdown
        required: false
        buttons: []
        editor_components: []
        sanitize_preview: true
        minimal: true
        pattern: ["^.{1,150}$","Vous êtes limité à 150 caractères"]
      - name: competences
        hint: "Vous pouvez choisir plusieurs compétences (n'hésitez pas à nous en proposer de nouvelles !)"
        widget: select
        multiple: true
        options: [
          "UX", 
          "UI", 
          "Développement Frontend", 
          "Développement Backend", 
          "Administration Système", 
          "Gestion de Produit", 
          "Coaching", 
          "Communication", 
          "Croissance", 
          "Administration Publique"
        ]
  - name: incubators
    publish: false
    label: Incubateurs
    label_singular: Incubateur
    folder: "content/_incubators"
    create: true
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: Nom, name: title, widget: string }
      - { label: Responsable, name: owner, widget: string }
      - { label: Site, name: website, widget: string }
      - { label: Dépôts des produits, name: github, widget: string }
      - { label: Contact, name: contact, widget: string }
      - { label: Adresse, name: address, widget: string }
      - label: Redirections
        label_singular: Redirection
        name: redirect_from
        widget: list
        collapsed: false
        field: { label: Source, name: name, widget: string }
  - name: phases
    label: Phases
    label_singular: Phase
    folder: "content/_phases"
    delete: false
    publish: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: status, name: status, widget: string }
      - { label: label, name: label, widget: string }
      - { label: type_label, name: type_label, widget: string }
      - { label: order, name: order, widget: number }
      - { label: short_description, name: short_description, widget: string }
  - name: events
    publish: false
    label: Évènement de SET
    label_singular: Évènement
    folder: "content/_events"
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: label, name: label, widget: string }
  - name: jobs
    identifier_field: roles
    label: Fiche de postes
    label_singular: Fiche de poste
    folder: "content/_jobs"
    create: true
    delete: false
    preview_path: "recrutement/{{year}}/{{month}}/{{day}}/{{roles}}"
    summary: "{{startup}} - {{filename}}"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    publish: false
    editor:
      preview: false
    fields:
      - label: >
          Quel est le titre du poste ? (exemple : "Développeuse - Développeur" ou "Chargée ou chargé de déploiement")
        name: roles
        widget: string
        required: true  
        hint : Penser à inclure le féminin dans vos recrutements. Vous pouvez trouver de l'aide sur l'écriture inclusive sans point médian dans [le guide de beta](https://doc.incubateur.net/communaute/travailler-a-beta-gouv/jutilise-les-outils-de-la-communaute/gitbook/recommandations#syntaxe) .
      - label: Est-ce que le poste est ouvert ?
        name: open
        widget: boolean
        required: true 
      - label: Est-ce que le poste est ouvert au junior ?
        name: junior
        widget: boolean
        required: false
      - label: Date de publication
        name: date
        widget: datetime
        time_format: false
        hint: "Uniquement si vous publiez la fiche plus tard"
      - label: Pour quelle startup ?
        label_singular: Startup
        hint: "Si la startup n'apparaît pas encore dans la liste, contacte un administrateur du site !"
        name: startup
        <<: *relation_default_options
        collection: startups
        required: false 
      - label: Rédiger sa fiche de recrutement
        name: body
        widget: markdown
        hint: N'hésite pas à te référer aux autres fiches de recrutement présentes sur le site beta.gouv et à utiliser le féminin dans tes recrutements en utilisant une écriture inclusive sans point médian.
        default: >
          Voici un exemple de format - N'hésite pas à utiliser les outils de mis-en-forme ou à switcher en markdown ☝️.
          Pour t'aider dans la rédaction de ta fiche produit, tu peux t'inspirer des dernières offres disponibles sur le [site de beta](https://beta.gouv.fr/recrutement/) et nous te recommandons de suivre ce plan:
          
          ## Le contexte
          Quel est le contexte de ta Startup d'Etat ?

          ## Le produit (ou la solution)
          Quelle est la cible ?
          A quoi ça sert ?

          ##L'équipe
          Qui compose l'équipe ?

          ## La mission
          Quelles seront les missions attendues ?

          ## Les savoir-être de la personne recherchée
          Quels sont les savoir-être indispensable pour bosser avec ton équipe ?

          ## Les modalités
          Poste ouvert pour ...
          Temps de travail : ... jours / semaine
          Démarrage en Mois Année
          Télétravail et/ou possibilité de travailler à ....

          Candidature à recrutement@beta.gouv.fr
