name: Sync 'authors' content with blog.beta.gouv.fr
on:
  workflow_dispatch:
  push:
    branches: ['master']

jobs:
  sync:
    runs-on: ubuntu-18.04
    steps:
    - name: Sync
      uses: adrianjost/files-sync-action@v1.0.1
      with:
        FILE_PATTERNS: |
          ^content/_authors/
          ^img/authors/
        TARGET_REPOS: |
          betagouv/blog.beta.gouv.fr
        GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}
