name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - uses: actions/cache@v2
      with:
        path: |
          vendor/bundle
          ~/.local
          ~/.cache
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install npm dependencies
      run: npm install
    - name: Install dependencies
      run: bundle check || bundle install --path vendor/bundle
    - name: Unit tests
      run: ruby -e "Dir.glob('rb/test/*.rb').each { |f| require File.expand_path(f) }"

    - name: Check author metadata
      run: ruby rb/bin/validate rb/schema/authors.yml "content/_authors/*.md"

    - name: Check startup metadata
      run: ruby rb/bin/validate rb/schema/startups.yml "content/_startups/*.md"
      
    - name: "Check authors file name structure (first_name.last_name.md)"
      run: |
            if ls content/_authors | grep --line-regexp --invert-match '[a-z_-]\+\.[a-z_-]\+\.md'
            then cat <<EOF
              One or more authors do not have the expected structure.
              Contact a website administrator if your generated author file breaks the validator.
              Notes:
              A dot (.) can only appear as a separator between the first and the last names.
              Dashes in names are kept as-is.
              Spaces are replaced by underscores (_).
              File extension must be '.md'
            EOF
              exit 1
            fi
            
    - name: Check Jekyll configuration
      run: bundle exec jekyll doctor

    - name: Jekyll build
      run: bundle exec jekyll build

    - name: Check homepage was compiled
      run: test -s _site/index.html

    - name: Check HTML common mistakes
      run: bundle exec htmlproofer ./_site --assume-extension --check-html --disable-external --empty-alt-ignore --check-img-http

    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: _site
        extra: --ignore 'Element "img" is missing required attribute "src"'

    - name: Lint JSON API pages
      run: bundle exec jsonlint _site/api/v*/*.json

    - name: Wait for server to start
      run: |
          (bundle exec jekyll serve --no-watch --skip-initial-build)&
          while ! curl --silent http://localhost:4000
          do sleep 1
          done 
